### PR TITLE
Change IRC info on community page from freenode to libera

### PR DESCRIPTION
**Pull request by rene-dev**
There are already around 50 users in the libera channel.
Buildbot and logs need to be configured to the new server.

### CODE REVIEW

**Comment by jepler** [comment]
Thanks!  I agree, but will not merge this right away in case any other active community members want to weigh in.

Short version of my viewpoint:
 * We have a decade of trust in the folks who are now running libera, from when they ran freenode
 * We already have a high profile mis-step by the new management of freenode, in an apparent attempt to suppress discussion of alternative systems
 * We have the example of other respected organizations already making the switch (centos and wikimedia foundation being the first two that come to mind)

I'll chat with @SebKuzminsky out of band and see about getting buildbot communicating with libera.

**Comment by jepler** [comment]
I'm also chatting with Tom_L about possibly getting the logger running on libera.

**Comment by rene-dev** [comment]
I could not find a way to link to the webchat and include the channel

**Comment by jethornton** [comment]
Is there a way to have a separate channel for the buildbot like 
linuxcnc_build? Doing that would keep the buildbot from interrupting 
conversations on linuxcnc_dev.

JT

**Comment by jepler** [comment]
If possible we'll put the buildbot output in a new channel.  I don't know why that would be a problem.  Anyway, I haven't heard from Seb yet.

**Comment by andypugh** [comment]
I am not sure that I am in favour of keeping the buildbot messages out of -dev. Whilst I agree that they are intrusive, I think that they should be. 
The context of this opinion is that I only discovered that there is an emc-commit mailing list last week. 10 years after starting with LinuxCNC, and  a year after taking on 2.8 release manager.

**Comment by rene-dev** [comment]
I agree with andy, it's better to fix the problems than to silence them.

**Comment by SebKuzminsky** [comment]
The buildbot now shows up in #linuxcnc-devel on libera.chat.  All the usual announcements and commands should work.  I'm happy to move it to some other channel (#linuxcnc-ci?) if that's what people want.

**Comment by jethornton** [comment]
#linuxcnc-ci works for me.

JT

**Pull request merged**
