### PR TITLE
Landing page typos fixed

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by andypugh** [comment]
I agree with 3D, but I don't see the point in editing an invisible comment (and I think that the "that" that you deleted was correct). Is it possible that replacing three dots with an elipsis character might cause problems on some systems?

**Comment by comradekingu** [comment]
@andypugh Both are a lot easier on blind or vision impaired people using screen readers.

**Comment by andypugh** [comment]
Do you think that there are blind CNC users? I have occasionally wondered if it could be done, but thought that it would be impossibly difficult.

**Review by jepler — APPROVED** [review]
Thank you!

**Pull request merged**
