### PR TITLE
Add links to translated master documentation.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
I like the addition of separate links for 2.9 and master aka devel aka 2.10.

The 2.9 pdf link is wrong.

The links to the translated docs don't point to the correct place (should be e.g. http://linuxcnc.org/docs/2.9/html/nb/).

Both 2.9 and devel should have translation links, not just devel.

The formatting is wrong when I build it on bullseye, missing line break:
Screenshot from 2022-12-01 16-39-30

... But all that said, I think a better place to put the translation links would be at the top of the index page http://linuxcnc.org/docs/2.9/html/ (and master).  That page is built from `linuxcnc/docs/src`.  The LinuxCNC build system has a chance of knowing what translations were actually built, whereas the wlo "Documents" page would have to be updated manually whenever the set of languages changes.

**Comment by silopolis** [comment]
Le ven. 2 déc. 2022 à 00:48, Sebastian Kuzminsky ***@***.***>
a écrit :

> I like the addition of separate links for 2.9 and master aka devel aka
> 2.10.
>
Show time ! 😍

**Comment by petterreinholdtsen** [comment]
[Sebastian Kuzminsky]
> I like the addition of separate links for 2.9 and master aka devel aka 2.10.
>
> The 2.9 pdf link is wrong.

Ah, right.  Fixed.

> The links to the translated docs don't point to the correct place
> (should be e.g. http://linuxcnc.org/docs/2.9/html/nb/).

Ah, yes.

> Both 2.9 and devel should have translation links, not just devel.

I decied to wait with 2.9 links until we got the formatting the way we
want it.

> The formatting is wrong when I build it on bullseye, missing line break:
> Screenshot from 2022-12-01
> 16-39-30

Right.  Tried again.

> ... But all that said, I think a better place to put the translation
> links would be at the top of the index page
> http://linuxcnc.org/docs/2.9/html/ (and master).  That page is built
> from `linuxcnc/docs/src`.  The LinuxCNC build system has a chance of
> knowing what translations were actually built, whereas the wlo
> "Documents" page would have to be updated manually whenever the set of
> languages changes.

I agree.  I'll see what can be done with docs/src/index.tmpl.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
https://github.com/LinuxCNC/linuxcnc/pull/2176

**Comment by hansu** [comment]
>I like the addition of separate links for 2.9 and master aka devel aka 2.10.

But I guess you are not meaning #27: https://github.com/LinuxCNC/wlo/pull/27/files ?

**Comment by petterreinholdtsen** [comment]
Placed translation links in the documentation instead of the web site.  This pull request no longer is relevant.

**Pull request closed without merging**
